"""empty message

Revision ID: 26584e4c4a92
Revises: 
Create Date: 2025-10-18 20:51:12.612654

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26584e4c4a92'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('location')
    )
    op.create_table('sensor_datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('temp', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('humi', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('record_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location'], ['locations.location'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_datas')
    op.drop_table('locations')
    # ### end Alembic commands ###
