"""empty message

Revision ID: 279a1b8567cd
Revises: ce4828fc4804
Create Date: 2025-10-25 18:41:00.010829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279a1b8567cd'
down_revision = 'ce4828fc4804'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('lecture_name', sa.String(length=200), nullable=False),
    sa.Column('professor', sa.String(length=200), nullable=False),
    sa.Column('day', sa.String(length=200), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('classroom', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lectures')
    # ### end Alembic commands ###
