"""empty message

Revision ID: 332a239984c8
Revises: e6b0f81310ef
Create Date: 2025-11-02 15:13:57.050852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332a239984c8'
down_revision = 'e6b0f81310ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=False),
    sa.Column('check', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_member')
    # ### end Alembic commands ###
