"""Initial migration for MySQL

Revision ID: a17d41b159cb
Revises: 
Create Date: 2026-02-03 10:52:32.710792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a17d41b159cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('std_num', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('std_num')
    )
    op.create_table('class_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('position', sa.String(length=20), nullable=False),
    sa.Column('check', sa.Boolean(), nullable=False),
    sa.Column('this_week', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lectures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('grade', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('lecture_name', sa.String(length=200), nullable=False),
    sa.Column('professor', sa.String(length=200), nullable=False),
    sa.Column('day', sa.String(length=200), nullable=False),
    sa.Column('period', sa.Integer(), nullable=False),
    sa.Column('classroom', sa.String(length=200), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('purpose', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('location')
    )
    op.create_table('recommend',
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('recommend_temp', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('month')
    )
    op.create_table('month_datas',
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('avg_temp', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('avg_humi', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['location'], ['locations.location'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('month', 'location')
    )
    op.create_table('sensor_datas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('temp', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('humi', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('record_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['location'], ['locations.location'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor_datas')
    op.drop_table('month_datas')
    op.drop_table('recommend')
    op.drop_table('locations')
    op.drop_table('lectures')
    op.drop_table('class_member')
    op.drop_table('admins')
    # ### end Alembic commands ###
