"""empty message

Revision ID: b0a32554539e
Revises: 332a239984c8
Create Date: 2025-11-02 17:09:47.077580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0a32554539e'
down_revision = '332a239984c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('this_week', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_member', schema=None) as batch_op:
        batch_op.drop_column('this_week')

    # ### end Alembic commands ###
