"""empty message

Revision ID: ce4828fc4804
Revises: 26584e4c4a92
Create Date: 2025-10-20 01:46:05.253043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce4828fc4804'
down_revision = '26584e4c4a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('std_num', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('std_num')
    )
    op.create_table('recommend',
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('recommend_temp', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('month')
    )
    op.create_table('month_datas',
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('avg_temp', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('avg_humi', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.ForeignKeyConstraint(['location'], ['locations.location'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('month', 'location')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('month_datas')
    op.drop_table('recommend')
    op.drop_table('admins')
    # ### end Alembic commands ###
